"use client";
import { deriveViewStatus } from "@/lib/request-status";
import { useState } from "react";
import Link from "next/link";
import { ScrollText, Flag, Users, ShieldCheck, ArrowUpRight } from "lucide-react";
import MobileSectionSelect from "@/components/mobile-section-select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Button } from "@/components/quest-ui/button";
import { useRecords, PageHeading, EmptyState, LoadState, RequestRow, QuestCard } from "@/components/quest-workspace";
export default function ReceptionPage() { const state = useRecords(["/api/requests", "/api/quests"]); const requests = state.data?.[0]?.requests || [], quests = state.data?.[1]?.quests || []; const [tab, setTab] = useState("review"); const groups = [{ id: "review", label: "依頼の確認", icon: ScrollText, items: requests.filter(x => deriveViewStatus(x,"reception") === "確認前"), help: "内容と条件を確認し、依頼者と合意しましょう。" }, { id: "publish", label: "公開の準備", icon: Flag, items: requests.filter(x => x.status === "合意済み"), help: "合意した依頼をクエストとして公開します。" }, { id: "select", label: "冒険者の選定", icon: Users, items: quests.filter(x => x.status === "募集中"), help: "応募者を確認し、クエストを任せる仲間を選びます。" }, { id: "complete", label: "完了報告の確認", icon: ShieldCheck, items: quests.filter(x => x.status === "完了報告済み"), help: "成果と写真を確認し、クエストの達成を承認します。" }]; return <div className="page-wrap reception-dashboard"><PageHeading eyebrow="GUILD COMMAND" title="受付デスク" description="届いた依頼を、次の冒険へ。"><Button asChild variant="outline"><Link href="/requests">すべての依頼<ArrowUpRight size={16}/></Link></Button></PageHeading><section className="guild-banner"><div><p className="eyebrow">THE GUILD LEDGER</p><h2>冒険を支える、あなたの仕事。</h2><p>{state.loading ? "ギルドの状況を確認しています。" : `現在 ${groups.reduce((n, g) => n + g.items.length, 0)} 件の案件が対応を待っています。`}</p></div></section><Tabs value={tab} onValueChange={setTab}><MobileSectionSelect label="対応する業務" value={tab} onChange={setTab} groups={groups}/><div className="stat-grid">{groups.map(({ id, label, icon: Icon, items }) => <button className={`stat-tile ${tab === id ? "selected" : ""}`} key={id} onClick={() => setTab(id)} aria-pressed={tab === id}><Icon size={21}/><span>{label}</span><strong>{state.loading ? "—" : items.length}<small>件</small></strong></button>)}</div><div className="panel"><div className="tab-scroll"><TabsList className="guild-tabs" variant="line">{groups.map(g => <TabsTrigger key={g.id} value={g.id}>{g.label}<span className="tab-count">{g.items.length}</span></TabsTrigger>)}</TabsList></div>{groups.map(g => <TabsContent key={g.id} value={g.id}><div className="panel-title"><h2>{g.label}</h2><p className="quiet text-sm">{g.help}</p></div><LoadState {...state}/>{!state.loading && !state.error && (g.items.length ? <div className={g.id === "select" || g.id === "complete" ? "quest-grid panel-grid" : ""}>{g.items.map(item => g.id === "review" || g.id === "publish" ? <RequestRow key={item.id} item={item} action={g.id === "publish" ? "公開する" : "確認する"} href={g.id === "publish" ? `/reception/questify?requestId=${item.id}` : `/requests/reception/${item.id}`}/> : <QuestCard key={item.id} quest={item} href={g.id === "complete" ? `/quests/${item.id}` : `/quests/${item.id}`} action={g.id === "complete" ? "報告を確認" : "応募者を選定"}/>)}</div> : <EmptyState title="この段階の対応待ちはありません" description="新しい依頼や報告が届くと、ここに表示されます。"/>)}</TabsContent>)}</div></Tabs></div>; }
