"use client";
import Link from "next/link";
import { useState } from "react";
import { Plus, ScrollText } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Button } from "@/components/quest-ui/button";
import { useSessionUser } from "@/lib/session-user";
import { useRecords, PageHeading, EmptyState, LoadState, RequestRow } from "@/components/quest-workspace";
export default function RequestsPage() { const { user } = useSessionUser(); const [tab, setTab] = useState("all"); const staff = user?.userType === "staff"; const state = useRecords(["/api/requests"]); const requests = [...(state.data?.[0]?.requests || [])].sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt))); const groups = [{ id: "all", label: "すべて", items: requests }, { id: "pending", label: "受付・合意中", items: requests.filter(x => ["確認前", "合意待ち", "合意済み"].includes(x.status)) }, { id: "active", label: "冒険中", items: requests.filter(x => ["クエスト化済み", "受注済み", "クエスト進行中", "完了報告済み"].includes(x.status)) }, { id: "done", label: "完了", items: requests.filter(x => x.status === "完了") }, ...(!staff ? [{ id: "draft", label: "下書き", items: requests.filter(x => x.status === "下書き") }] : [])]; return <div className="page-wrap request-list-page"><PageHeading eyebrow="REQUEST LEDGER" title={staff ? "依頼管理" : "自分の依頼"} description={staff ? "託された願いと、その進み具合を確認します。" : "あなたが届けた依頼の進み具合を確認できます。"}>{!staff && <Button asChild><Link href="/requests/new"><Plus size={18}/>新しい依頼を書く</Link></Button>}</PageHeading><div className="ledger-intro desktop-request-ledger"><ScrollText size={30} strokeWidth={1}/><div><h2>{staff ? "ギルド依頼帳" : "あなたの依頼帳"}</h2><p>{state.loading ? "読み込み中…" : `${requests.length} 件の依頼`}</p></div></div><Tabs value={tab} onValueChange={setTab} className="panel"><div className="mobile-request-filter"><label htmlFor="request-status-filter">表示する依頼</label><select id="request-status-filter" value={tab} onChange={event => setTab(event.target.value)}>{groups.map(g => <option key={g.id} value={g.id}>{g.label}（{g.items.length}件）</option>)}</select></div><div className="tab-scroll"><TabsList variant="line" className="guild-tabs">{groups.map(g => <TabsTrigger key={g.id} value={g.id}>{g.label}<span className="tab-count">{g.items.length}</span></TabsTrigger>)}</TabsList></div>{groups.map(g => <TabsContent key={g.id} value={g.id}><LoadState {...state}/>{!state.loading && !state.error && (g.items.length ? g.items.map(item => <RequestRow key={item.id} item={item} href={`/requests/${staff ? "reception" : "requester"}/${item.id}`}/>) : <EmptyState title={g.id === "all" ? "依頼帳は、まだ白紙です" : "この状態の依頼はありません"} description={!staff ? "解決したいことを、ギルドに届けましょう。" : undefined}>{!staff && g.id === "all" && <Button asChild variant="outline"><Link href="/requests/new"><Plus size={16}/>最初の依頼を書く</Link></Button>}</EmptyState>)}</TabsContent>)}</Tabs></div>; }
