"use client";
import { appPath } from "@/lib/app-path";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Compass, LayoutDashboard, ScrollText, LogOut, Swords, Settings, Menu, ArrowLeft, X } from "lucide-react";
import { SidebarProvider, Sidebar, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
function NavigationLink(props) { const { setOpenMobile } = useSidebar(); return <Link {...props} onClick={() => setOpenMobile(false)}/>; }
function MobileMenuButton() { const { toggleSidebar, openMobile, isMobile } = useSidebar(); return <button type="button" className="mobile-menu-button" disabled={!isMobile} onClick={toggleSidebar} aria-label="メニューを開閉" aria-expanded={openMobile}><Menu size={22}/></button>; }
function AgencySidebar(props) { const { isMobile } = useSidebar(); return <Sidebar {...props} side={isMobile ? "right" : "left"}/>; }
function MobileMenuCloseButton() { const { setOpenMobile } = useSidebar(); return <button type="button" className="mobile-menu-button self-end" onClick={() => setOpenMobile(false)} aria-label="メニューを閉じる"><X size={22}/></button>; }
export default function AgencyShell({ user, children }) {
    const path = usePathname();
    if (!user)
        return children;
    const staff = user.userType === "staff";
    const pageTitle = path === "/requests" ? (staff ? "依頼管理" : "自分の依頼") : path === "/requests/new" ? "新しい依頼を書く" : path.endsWith("/adjust") ? "条件の調整を提案" : path.startsWith("/requests/") ? "依頼書を確認" : path === "/settings" ? "ユーザー設定" : path === "/reception" ? "受付デスク" : path === "/adventurer" ? "クエストボード" : path.includes("/reviews/") ? "クエストの進捗・報告" : path.includes("questify") ? "クエストの公開" : path.startsWith("/reception/quests/") ? "冒険者の選定" : "クエスト詳細";
    const mobileBackHref = path.endsWith("/adjust") && path.startsWith("/requests/") ? path.slice(0, -7) : path.startsWith("/requests/") ? "/requests" : path.startsWith("/reception/") ? "/reception" : path.startsWith("/quests/") ? (staff ? "/reception" : "/adventurer") : path.startsWith("/adventurer/quests/") ? "/adventurer" : null;
    const mobileBackLabel = path.endsWith("/adjust") ? "依頼書へ戻る" : path.startsWith("/requests/") ? "依頼一覧へ戻る" : path.startsWith("/reception/") ? "受付デスクへ戻る" : "クエスト一覧へ戻る";
    const links = staff ? [{ href: "/reception", label: "受付デスク", icon: LayoutDashboard }, { href: "/requests", label: "依頼管理", icon: ScrollText }] : [{ href: "/adventurer", label: "クエストボード", icon: Swords }, { href: "/requests", label: "自分の依頼", icon: ScrollText }];
    links.push({ href: "/settings", label: "ユーザー設定", icon: Settings });
    return <SidebarProvider className="agency-shell" style={{ "--sidebar-width": "15rem" }}><a href="#workspace" className="skip-link">本文へ移動</a><AgencySidebar className="agency-sidebar"><SidebarHeader className="p-7"><MobileMenuCloseButton/><Link href={staff ? "/reception" : "/adventurer"} className="agency-brand"><Compass size={34}/><span>QUEST<span className="brand-sub">異世界クエスト斡旋所</span></span></Link></SidebarHeader><SidebarContent className="px-4 py-6"><p className="nav-caption">{staff ? "GUILD OFFICE" : "ADVENTURER"}</p><SidebarMenu>{links.map(({ href, label, icon: Icon }) => <SidebarMenuItem key={href}><SidebarMenuButton asChild isActive={path.startsWith(href)} className="agency-nav-link"><NavigationLink href={href}><Icon /><span>{label}</span></NavigationLink></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="p-5"><div className="account-block"><span className="account-avatar">{user.displayName?.slice(0, 1) || "Q"}</span><div><strong>{user.displayName}</strong><span>{staff ? "ギルド受付" : "依頼者・冒険者"}</span></div></div><a href={appPath("/signout-with-chatgpt?return_to=/")} target="_top" className="signout-link"><LogOut size={16}/>ログアウト</a></SidebarFooter></AgencySidebar><div className="workspace-frame" data-mobile-back={Boolean(mobileBackHref)}><header className="workspace-bar"><div className="desktop-header-content flex items-center gap-3"><SidebarTrigger className="desktop-sidebar-trigger" aria-label="メニューを開閉"/><span className="desktop-workspace-label">{staff ? "ギルド受付" : "冒険者の広場"}</span></div><div className="mobile-header-content"><div className="mobile-back-slot">{mobileBackHref && <Link href={mobileBackHref} className="mobile-back-button" aria-label={mobileBackLabel}><ArrowLeft size={22}/></Link>}</div><h1 className="mobile-page-title">{pageTitle}</h1><MobileMenuButton/></div><span className="workspace-brand-note">ISEKAI QUEST AGENCY</span></header><main id="workspace" className="workspace-content">{children}</main></div></SidebarProvider>;
}
