"use client";
import PublicQuestDetails from "@/components/public-quest-details";
import RequestAttachments from "@/components/request-attachments";
import { useState } from "react";
import { useSessionUser } from "@/lib/session-user";
import { Coins, MapPin, Users, Shield, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Status } from "@/components/quest-workspace";
export default function QuestDossier({ quest, backHref, children }) { const [mobilePane, setMobilePane] = useState("details"); const {user}=useSessionUser(); const staff=user?.userType==='staff'; const actionLabel=staff?(quest.status==='募集中'?'冒険者を選定':quest.status==='完了報告済み'?'成果を確認':quest.status==='達成確認済み'?'達成の記録':'進捗を確認'):(quest.status==='募集中'?(quest.applicants?.length?'申請状況':'参加を申請'):'報告・進捗'); return <><Link className="back-link" href={backHref}><ArrowLeft size={16}/>一覧に戻る</Link><header className="dossier-heading"><span className="rank-seal">{quest.rank || "—"}<small>RANK</small></span><div><p className="eyebrow">GUILD QUEST</p><h1>{quest.title}</h1><p>{quest.deadline ? `完了期限：${quest.deadline}` : "条件を確認し、冒険に備えましょう。"}</p></div><Status value={quest.status}/></header>{quest.canViewSourceRequest && <div className="mb-4"><Link className="text-sm text-primary underline underline-offset-4" href={`/requests/${staff ? "reception" : "requester"}/${quest.requestId}?document=1`}>元の依頼書・条件の調整を見る</Link></div>}<div className="mobile-dossier-navigation" role="group" aria-label="クエストの表示"><button aria-pressed={mobilePane === "details"} onClick={() => setMobilePane("details")}>依頼内容</button><button aria-pressed={mobilePane === "actions"} onClick={() => setMobilePane("actions")}>{actionLabel}</button></div><div className="quest-meta-grid" data-mobile-pane={mobilePane}>{[[Coins, "報酬", quest.reward], [Users, "募集人数", quest.slots], [MapPin, "場所", quest.location], [Shield, quest.publishVersion ? "参加条件" : "危険度", quest.publishVersion ? (quest.minimumRank ? `${quest.minimumRank}ランク以上` : "ランク制限なし") : quest.risk]].map(([Icon, label, value]) => <div key={label}><Icon size={18}/><span>{label}</span><strong>{value || "未設定"}</strong></div>)}</div><div className="dossier-columns" data-mobile-pane={mobilePane}><section className="guild-document"><header className="document-heading"><h2>クエストの詳細</h2></header>{quest.publishVersion ? <div className="document-body"><PublicQuestDetails quest={quest}/></div> : <dl className="document-details document-body">{[["任務の内容", quest.detail], ["成果物・達成条件", quest.deliverables], ["ギルド支給物", quest.supplies], ["地図・注意事項", quest.mapNotes], ["連絡方法", quest.channel], ["担当受付", quest.receptionistName], ["参加する冒険者", quest.adventurerName]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "未設定"}</dd></div>)}<div><dt>依頼の添付ファイル</dt><dd><RequestAttachments files={quest.requestAttachments||[]}/></dd></div></dl>}</section><div className="dossier-actions">{children}</div></div></>; }
